name: linting

on: [pull_request]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        depth: 1
        submodules: 'recursive'
    - name: Run Cppcheck
      uses: Bedzior/cppcheck-action@v1.0
      with:
        enabled checks: all
        enable inconclusive: true
        generate report: true
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: output

