name: linting

on: [pull_request]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        depth: 1
        submodules: 'recursive'
    - name:  Install Cppcheck
      run: |
        sudo apt-get install -y cppcheck
    - name:  Run Cppcheck
      run: |
        cppcheck $GITHUB_WORKSPACE/firmware --language=c++ --template="::{severity} file={file},line={line},col={column}::{message}" 
        ls $GITHUB_WORKSPACE


