name: linting

on: [pull_request]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: c-linter
        uses: tonybaloney/cppcheck-action@master
        with: 
          path: firmware

