name: linting

on: [pull_request]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: check folders
        run: ls
      - name: c-linter
        uses: tonybaloney/cppcheck-action@master
        with:
          path: /firmware
